declare module '*.jpeg';
declare module '*.jpg';
declare module '*.json';
declare module '*.png';
declare module '*.svg';
declare module 'react-vertical-timeline-component';
declare module 'react-pose';
declare module 'gatsby';
declare module 'react-particles-js';
